### ISSUE TITLE
[DataMigration] When deleting an array, the rollback returns an object instead of an array

### ISSUE THREAD

**Issue by raphael-nachar** [360Learning/mongo-bulk-data-migration#3]
# Context

When deleting an array using a `DataMigration` script, the rollback returns an object instead of an array.

# Specification

Fix this problem so that the rollback returns an array

### Think of the Mobile Apps!

No impact of the Mobile Apps

**Comment by pp0rtal** [comment]
@raphael-nachar Thanks for reporting!
this will be fix in next shipment 1.3.0
